
    spring.application.name=cricket-news-bot
    # Database
    spring.datasource.url=jdbc:mysql://localhost:3306/cricket_db
    spring.datasource.username=appuser
    spring.datasource.password=Adnanali@2004
    # JPA
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    spring.jpa.open-in-view=false
    # RSS
    cricket.rss.url=https://www.espncricinfo.com/rss/content/story/feeds/0.xml
    # Mastodon
    mastodon.instance.url=https://mastodon.social
    mastodon.access.token=zozjcQfe-sGrOFtgTLsPatwuhxFsqqs-4A8eWlH5b28
    # Logging
    logging.file.name=logs/cricketbot.log
    logging.logback.rollingpolicy.max-file-size=10MB
    logging.logback.rollingpolicy.max-history=7
    logging.level.root=OFF
    logging.level.com.cricketbot=INFO
    # Scheduling
    spring.task.scheduling.enabled=true